Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/08/2019
Var
// Seção de Declarações das variáveis 
 Numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("informe um numero real qualquer: ")
leia(numero)
escreva("O dobro é", Numero*2)

Fimalgoritmo